<div class="search-layer">
	<span class="close text-sm font-light">X</span>
	<form data-ajax="search" id="search" method="post" action="">
		<input class="search font-thin text-xl" type="text" id="input_search" name="post_title" placeholder="Search posts" autofocus>
	</form>
	<div class="search-results">
		<div class="loader">
			<div class="search-loader">
			</div>
			<h4 class="text-md font-thin"> Fetching data, please wait.. </h4>
		</div>
			<div class="index-post-container" id="search-container">
			</div>		
	</div>
</div>