<div class="about-me">
	<h1 class="font-light text-xl text-heading-green">
	About this website
	</h1>
	<p class="bla-bla text-sm font-regular text-dark">
	Hello. <br/><br/> My name is Konstantin and i'am hope-soon-to-be junior web developer. This website suits the somewhat presentational purpose of my programming skills. It's core is made in PHP Zend Framework 3, and the front end mostly in Gulp, jQuery and SaSS. It is a humble little website, and i'am glad that is almost ready to launch. <br /> If it was all up to me, it would probably be launched in 2019 due to the ammount of detail i'am ready to commit myself daily putting in every aspect of this website. Well... Thanks to Alex i stripped it to the nearly bone strucutre, to be functional and simple. <br />
	I learned alot during this lets-call-it excersise, and figured out that this is what i wanna spend my time doing.
	<br /> <br />This site will mostly be writtings about my experiences with programming, and probably something personal in the future. There are some stuff that needs to be done, for me to be writting a presentational article. <br /> <br />
	Anyway, whoever you are for whatever reason you are reading this, thanks for beign here and enjoy your stay :)
	</p>
</div>