<div class="contact-form">
    <div class="error-field">
    </div>
    <h1 class="font-light text-xl text-heading-green">Contact </h1>
    <div class="contact-form-wrap">
		<form data-ajax="true">
			<input class="text-xs font-regular input-comment contact-input" type="text" name="contact_name" id="contact-name" placeholder="Your Name" />
			<input class="text-xs font-regular input-comment contact-input" type="text" name="contact_email" id="contact-email" placeholder="Your email" />	
			<input class="text-xs font-regular input-comment contact-input" type="text" name="contact_subject" id="contact-email" placeholder="Subject" />								
			<textarea rows="20" class="text-xs font-regular textbox-comment contact-textarea" name="contact_body" placeholder="Your message" id="contact-body" /></textarea>
			<input class="text-sm font-medium comments-submit" type="submit" name="submit" id="submit-contact" />
		</form>	    
    </div>
</div>