<div class="post-readfull-wrap">
</div>
<hr class="comment-divider">
<div class="post-comments">
    <div class="error-field">
    </div>
    <h2 class="text-md font-light"> Comments </h2>
	<div class="comments-form-wrapper">
		<form data-ajax="true">
			<input class="text-xs font-regular input-comment" type="text" name="comment_name" id="comment-name" placeholder="Name" />
			<textarea class="text-xs font-regular textbox-comment" name="comment_body" placeholder="Your message" id="comment-body" /></textarea>
			<input class="text-sm font-medium comments-submit" type="submit" name="submit" id="submit-comment" />
		</form>
	</div>
	<div class="comments-list">
	</div>
</div>